### ISSUE TITLE
suggestion: making github status both cards in single row

### ISSUE THREAD

**Issue by NirmalSilwal** [saviomartin/saviomartin#1]
Hi @saviomartin , I think if you put github stats and most used language stat in single row, you could cut down extra spaces in your profile. 
Even "**connect with me**" and **"my skills"** sections if adjusted in single row, would make your profile look much better. 

This is just my view.

What do you think?

**Comment by saviomartin** [comment]
@NirmalSilwal, Hi bro

Thank you for the suggestion. I really appreciate that.
but In my view, I felt **irritated** on seeing **both the card on the same line with height variation.**

Yet, **Thanks for the suggestion**
